### ISSUE TITLE
New Collection Request

### ISSUE THREAD

**Issue by way2rach** [0xsequence/niftyswap-directory#13]
### Collectible Name

Shrub Paper Gardens

### Contract Address

https://polygonscan.com/address/0xa9ae86b25424d8b523a91975da1336ac490bc4c7

### Project Link

https://gardens.shrub.finance/

### Network Name

Polygon Mainnet

### Description

The first interactive on-chain growth NFT. Shrub.finance's genesis NFT project is the most technically advanced NFT series yet. In this series you plant a seed and grow it into a Shrub all on the Polygon blockchain. Dynamic metadata means you watch it grow on OpenSea. Join us in this groundbreaking series.

**Comment by acrylix** [comment]
@way2rach thanks for submitting a listing request!

a lot of assets have broken metadata in this collection

![image](https://user-images.githubusercontent.com/1619025/192886012-84995bab-2cb3-4a4a-a5ae-ebb465dfc7d7.png)

**Comment by acrylix** [comment]
@way2rach interesting mechanism, so the burned token IDs will never be used again?

**Comment by acrylix** [comment]
we will soon introduce filters that can be used to exclude burned tokens in the results, but in the mean time it will show as broken metadata, let me know if you are fine with this

**Comment by way2rach** [comment]
> @way2rach interesting mechanism, so the burned token IDs will never be used again?

That is correct. This is for instance how potted plant NFTs convert to Shrub NFTs. Our users have really enjoyed this mechanism. :)


> we will soon introduce filters that can be used to exclude burned tokens in the results, but in the mean time it will show as broken metadata, let me know if you are fine with this
That would be awesome! We are happy in the meantime to be listed with the broken metadata. 
Thanks for working on making this happen <3

**Comment by acrylix** [comment]
@way2rach added to the direcotry https://github.com/0xsequence/niftyswap-directory/commit/a6cb7f18235c212001df1c2c2fab45143925cbb7

feel free to join our discord if you have any other questions / feedback https://discord.com/invite/niftyswap
